config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  devise_for :users, controllers: { registrations: 'users/registrations' }

   
  get 'accounts/:id' => 'accounts#show'
  post 'accounts/:id'=> 'accounts#course'
  get '/courses' => 'courses#index'
  patch '/courses/:id/add_students' => 'courses#add_students', :as => :add_student
  get '/courses/new' => 'courses#new'
  get '/courses/:id' => 'courses#show'
  post "/courses" => "courses#create"
  post "/courses/:id/request_join_team" => "courses#request_join_team", :as => :request_join_team

	get "/teams/new" => "teams#new"
  post "/teams" => "teams#create"
  get '/teams/:id/message_board' => 'teams#message_board'
  post "/teams/:id/message_board" => "teams#create_message", :as => :create_message
  get '/teams/:id/student_requests' => 'teams#student_requests'
  post "/teams/:id/approve_or_reject_join_team" => "teams#approve_or_reject_join_team", :as => :approve_or_reject_join_team

  get "/teams/:team_id/tasks" => "tasks#index"
  get '/teams/:team_id/tasks/:id/edit' => 'tasks#edit'
  #get "/teams/:team_id/tasks/:id" => 'tasks#show'
  post '/teams/:team_id/tasks/' => 'tasks#create'
  delete '/teams/:team_id/tasks/:id' => 'tasks#destroy'
  patch '/teams/:team_id/tasks/:id' => 'tasks#update'
  
  post "/teams/:team_id/tasks/bulk_update" => "tasks#bulk_update"
  post "/teams/:team_id/tasks/:id/remove_user/:user_id" => "tasks#remove_user"
  post "/teams/:team_id/tasks/:id/set_complete" => "tasks#set_complete"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index
        if current_user.is_student?
            flash[:warning] = "Your user account type is not authorized to view all courses."
            redirect_to "/accounts/#{current_user.id}" and return
        end

        # @courses = Course.where(instructor_id: current_user.id)
        @courses = Course.all
    end

    def add_students
        user = User.find(params[:student_id])
        course = Course.find(params[:id])

        if course.users.where(id: user.id).empty?
            course.users << user
            flash[:success] = "#{user.name} has been registered to #{course.code}"
        else
            if user.is_student
                flash[:danger] = "This student is already registered to #{course.code}"
            else
                flash[:danger] = "This instructor is already registered to #{course.code}"
            end
        end    
        redirect_to '/courses'
    end

    def show 
        @course = Course.find params[:id]
        @request = Request.new

        @student_on_team = false
        @course.teams do |team|
            team.users do |member|
                if member.id == current_user.id
                    @student_on_team = true
                end
            end
        end
    end

    def new
        @course = Course.new

        if current_user.is_student?
            flash[:warning] = "Your user account type is not authorized to create new courses."
            redirect_to "/courses/"
        end
    end

    def create
        @course = Course.new(course_params)
        @course.instructor_id = current_user.id

        current_user.courses << @course

        if @course.save
            flash[:success] = "New course created."
            redirect_to "/accounts/#{current_user.id}"
        else
            render 'new'
            flash[:danger] = "Error: Course creation failed."
        end
    end

    def request_join_team
        team = Team.find(params[:team_id])
        request = team.requests.find_by(student_id: current_user)
        if request.present?
            flash[:danger] = "There is already an active request for this user to this team."
            redirect_to "/courses/#{params[:id]}" and return
        end

        request = Request.new(student_id: current_user.id)
        team.requests << request

        if request.save
            flash[:success] = "New request created."
        else
            flash[:danger] = "Error: Request creation failed."
        end
        redirect_to "/courses/#{params[:id]}"
    end

    private

        def course_params
            params.require(:course).permit(:name, :code)
        end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class = "center-div">
    <h1 class="title-div">
        All Courses
    </h1>
    <% @courses.each do |course| %>

        <div class="card">
            <div class="card-body">
                <p>
                    <div class="course-full">
                        <h4>
                            <%= course.name %>    |    <%= course.code %>
                        </h4>
                    </div>
                    <div class="course-update">
                        <%= form_for course, :url => add_student_path(course.id) do |f| %>
                            <%= f.label(:add_student) %>
                            <%= select_tag :student_id, options_from_collection_for_select(User.where(is_student: true), 'id', 'name') %>
                            <%= f.submit "Update Student", class: "btn btn-success" %><br>
                        <% end %>
                    </div>
                    <div class="course-update">
                        <%= form_for course, :url => add_student_path(course.id) do |f| %>
                            <%= f.label(:add_instructor) %>
                            <%= select_tag :student_id, options_from_collection_for_select(User.where(is_student: false), 'id', 'name') %>
                            <%= f.submit "Update Instructor", class: "btn btn-success" %>
                        <% end %>
                    </div>
                </p>
            </div>
        </div>
        
    <% end %>
</div>

app/views/courses/new.html.erb
<div class='row'>
    <div class='col'>
    </div>
	<div class='col-5'>
		<% if @course.errors.full_messages.present? %>
			<ul>
				<% @course.errors.full_messages.each do |error| %>
					<li>
						<%= error %>
					</li>
				<% end %>
			</ul>
		<% end %> 
		<h1>Create Course</h1>
		<%= form_for(@course) do |f| %>
			<ul id="create-course"> 
				<li class="input-title"><%= f.label(:name) %></li>
				<li class="input"><%= f.text_field :name, autocomplete: "course name", placeholder:"Course Name", autofocus: true, class: "form-control" %></li>
				<li class="input-title"><%= f.label(:code) %></li>
				<li class="input"><%= f.text_field :code, autocomplete: "course code", placeholder:"Course Code", autofocus: true, class: "form-control" %></li>
				<li class="submit-btn"><%= f.submit "Create", class: "btn btn-danger" %></li>   
			</ul>
		<% end %>

	</div>
	<div class='col'>
	</div>
</div>

app/views/courses/show.html.erb
<head>
  <style>
  #teams {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
    text-align: center;
  }

  #teams td, #teams th {
    border: 1px solid #ddd;
    padding: 8px;
  }

  #teams tr:nth-child(even){background-color: #f2f2f2;}

  #teams tr:hover {background-color: #ddd;}

  #teams th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #dc3545;
    color: white;
  }

  .center {
    text-align: center;
  }
  </style>
</head>
<h1 class="center">
    <%= @course.name %>: Active Teams
</h1>

<table id = "teams">
  <th>Team Name</th>
  <th>Active Members</th>
  <th>Team Capacity</th>
  <th>Liaison</th>
  <th>Requests</th>
  <th>Active Requests</th>
  <% if !current_user.is_student %>
    <th>Message Board</th>
  <% end %>
  <th>Task List</th>
  <% @course.teams.each do |team| %>
      <tr>
        <td><%= team.name %></td>
        <td><%= team.users.count %></td>
        <td><%= team.maximum_capacity %></td>
        <td>
          <% liaison = User.where(id: team.liaison_id) if team.liaison_id.present? %>
          <% if liaison.present? %>
            <%= liaison[0].name %>
          <% end %>
        </td>
        <td class='center'>
          Number of requests: <%= team.requests.length%><br>
          <% if !current_user.is_student %>
            
          <% elsif @student_on_team %>
            Already on a team.
          <% elsif !team.requests.where(student_id: current_user.id).empty? %>
            Request Active
          <% elsif team.requests.length == team.maximum_capacity %>
            <%= button_to 'Team Full', request_join_team_path(params[:id], team_id: team.id), {class: "btn btn-outline-secondary", style: "pointer-events: none !important;"} %>
          <%else%>
            <%= button_to 'Request to Join', request_join_team_path(params[:id], team_id: team.id), {class: "btn btn-outline-success"} %>
          <% end %>
        </td>
        <td class='center'>
          <% if current_user.id == team.liaison_id || !current_user.is_student%>
            <%= link_to "Requests", "/teams/#{team.id}/student_requests", class: "btn btn-secondary" %>
          <% else %>
            N/A
          <% end %>
        </td>
        <% if !current_user.is_student %>
          <td class='center'>
              <%= link_to "Message Board", "/teams/#{team.id}/message_board", class: "btn btn-secondary" %>
          </td>
        <% end %>
        <td class='center'>
          <%= link_to "Task List", "/teams/#{team.id}/tasks", class: "btn btn-secondary" %>
        </td>
      </tr>
  <% end %>
</table>
<br>
<%= link_to "Create Team", "/teams/new", :class=>"btn btn-danger right" %>